[package]
name = "menu-control"
version = "0.5.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
serde_json = "1.0.118"
serde = { version = "1.0", features = ["derive"] }
crossterm = "0.27.0"
figlet-rs = "0.1.5"